### ISSUE TITLE
Package requires PHP 7.4, higher PHP versions are incompatible

### ISSUE THREAD

**Issue by VladiCz** [szymsza/php-ppl-create-package-label-api#1]
PHP version 8.X installed

Steps to reproduce:

composer require szymsza/ppl-create-package-label-api

Output:

In PackageDiscoveryTrait.php line 312:
                                                                                                                                          
  Package szymsza/ppl-create-package-label-api has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - szymsza/ppl-create-package-label-api v0.0.1 requires php ^7.4 which does not match your installed version 8.1.27.                   

Expected result:

composer package install success

**Comment by szymsza** [comment]
Thanks, I updated the package requirements. I did a quick test with PHP 8.1.29 and everything seems to be working.
