### ISSUE TITLE
FR: Allow PHP 7.3

### ISSUE THREAD

**Issue by david-vaclavek** [szymsza/php-ppl-create-package-label-api#2]
Hello @szymsza.

Is PHP 7.4 needed? Would it be possible to allow PHP 7.3?

Thanks for the clarifications.

**Comment by szymsza** [comment]
Hi, I did some minor changes and released a new version that supports 7.3. I did some simple tests with 7.3.33 and everything seems to be working fine. Feel free to open a new issue if you find any problems.

**Comment by david-vaclavek** [comment]
@szymsza Thanks for the quick update.
